pixelhandler/ember-jsonapi-resources

package.json

The blueprint can't be used unless `lodash` and `inflection` are in the `dependencies.

Add inflection and lodash to dependencies from devDependencies.

---

addon/adapters/application.js
addon/mixins/authorization.js
app/adapters/application.js
app/mixins/authorization.js
tests/unit/adapters/application-test.js
tests/unit/mixins/authorization-test.js

Adds a Mixin class for storage of credential/token for storage of a HTTP Authorization request-header credential.
The default solution is to use `localStorage['AuthorizationHeader']` (for the credential) to set the HTTP 'Authorization' request-header (which is assigned by the ApplicationAdapter#fetchOptions method after a call to ApplicationAdapter#fetch).
Adds a new method to the adapter `fetchAuthorizationHeader` which assigns the request-header using properties provided by the AuthorizationMixin `authorizationCredential` and `authorizationHeaderField`. 
The default value of the `authorizationHeaderField` property is `'AuthorizationHeader'`. The default behavior of the computed property `authorizationCredential` is to get/set `localStorage['AuthorizationHeader']`.
The mixin is combined …

[Feature] Authorization mixin for storage of request-header credentials

---

addon/adapters/application.js
tests/unit/adapters/application-test.js

According to JSON API v1.0 the PATCH request to update a relationship must include a top-level member named data containing a resource identifier object or null.

Add top-level data member to PATCH relationship

---

addon/models/resource.js

See: http://jsonapi.org/recommendations/#naming  and https://github.com/cerebris/jsonapi-resources#key-format
- `'first-name': attr()` is the JSON API recommendation
- `images: hasMany('image-assets')` and `image: hasOne('image-asset')` are preferred
Failed assertion handled by console.warn
[Closes #28]

Add assertion for dasherized keys in resource

---

addon/adapters/application.js
addon/models/resource.js
tests/helpers/resources.js
tests/unit/adapters/application-test.js

- Relationship helpers may use a String argument for the relation name,
as found in the relationship object of the JSON payload
- Helpers may instead use an Object argument with properties for relation
and type (type is different service) to use for fetching resource relations
[Fixes #36]

Add options argument for findOne/findMany Resource helpers

---

README.md
addon/adapters/application.js
addon/mixins/service-cache.js
addon/models/resource.js
addon/utils/attr.js
addon/utils/has-many.js
addon/utils/has-one.js
addon/utils/is.js
addon/utils/related-proxy.js
blueprints/model/files/__root__/__path__/__name__.js
tests/unit/models/resource-test.js
tests/unit/utils/attr-test.js
tests/unit/utils/has-many-test.js
tests/unit/utils/has-one-test.js
tests/unit/utils/is-test.js

- string, number, boolean, date, object, array may be set as the type of attribute
- reorganize modules for Resource helpers into utilities
- use `constructor.metaForProperty` instead of `proto._meta` for lookup of computed property meta values
- update README with use of attr() and optional types

attr() helper may use optional type

---

README.md
addon/adapters/application.js
addon/mixins/transforms.js
addon/serializers/application.js
addon/utils/transforms.js
app/mixins/transforms.js
app/serializers/application.js
fixtures/api/posts/1.json
tests/dummy/app/adapters/post.js
tests/dummy/app/models/author.js
tests/dummy/app/models/comment.js
tests/dummy/app/models/commenter.js
tests/dummy/app/models/employee.js
tests/dummy/app/models/picture.js
tests/dummy/app/models/post.js
tests/dummy/app/models/product.js
tests/dummy/app/templates/pictures/detail.hbs
tests/helpers/resources.js
tests/unit/adapters/application-test.js
tests/unit/mixins/transforms-test.js
tests/unit/serializers/application-test.js
tests/unit/utils/transforms-test.js

The application serializer has methods for [de]serializing the date values between client and server. An attribute that is setup as a `'date'` type also has a built in transform method to serialize and deserialize the date value. Typically the JSON value for a Date object is communicated in ISO format, e.g. "2015-08-25T22:05:37.393Z". 
The TransformsMixin defines `serializeDateAttribute` and `deserializeDateAttribute`. Any valid type can be added to your app, just generate a `transforms` mixin and define other types if needed. Or when you generate a resource add the type specific methods or attribute name specific methods on the serializer prototype (class) for your resource.
The methods use a naming convention '[de]serialize' + 'AttrName' or 'TypeName' + 'Attribute'; so to add a specific …

Add transform methods for [de]serializing resource attributes

---

addon/adapters/application.js
addon/mixins/fetch.js
addon/models/resource.js
addon/services/store.js
addon/utils/has-many.js
addon/utils/has-one.js
addon/utils/related-proxy.js
tests/unit/models/resource-test.js

- New resource uses mock relation in proxy relationship hasOne/hasMany
- Add Update Relationship method to Resource prototype
- Add header for `credentials` in fetch options (support for cookie session)
When a resource `isNew` has a `true` value (default is `false`) the resource does not yet have any URLs from the server. Since it's the server's job to inform that client of the relationship URLs a new resource will only use the [resource identifier objects](http://jsonapi.org/format/#document-resource-identifier-objects). The new Resource#updateRelationships object manages changes to the relationships data object(s).
By using the `Resource#updateRelationship` method you may update a relation by adding or removing using a list, id, or null. When adding an id for a to-many relation send one …

Resource updates, new behavior for relations

---

addon/adapters/application.js

The Adapter#createResource method accepts a resource argument, which is flexible to work with either a Resource instance or a plain object that represents a JSON API Resource.
Given the `createResource` method is called with a `Resource` (model) instance, use `then()` to update the resource instance and ensure the cached resource is same resource. (May replace a newly created resource by the deserialize method.)

Adapter#createResource may set props of resource instance

---

addon/utils/transform-map.js
blueprints/model-test/files/tests/unit/__path__/__test__.js
ember-cli-build.js
index.js
tests/unit/utils/transform-map-test.js

- Abstract class to transform mapped data structures
- Update build config for including test assets
- Pass all args to super included method in index.js
- Add registry.unregister use in afterEach section of model test blueprint

Add Transform Map Utility

---

addon/adapters/application.js
addon/mixins/fetch.js
addon/mixins/service-cache.js
addon/models/resource.js
tests/unit/adapters/application-test.js
tests/unit/models/resource-test.js

- (Breaking change) Removing event triggers `didUpdateResource` and `resourceError`
- Cache update after updating a resource (PATCH) is handled by model method, via `cacheUpdate`
- Support (client, 40x) text error response, parse text to JSON

Update cache handling for updates, remove evented update callbacks

---

addon/adapters/application.js
addon/models/resource.js
addon/serializers/application.js
blueprints/jsonapi-initializer/files/__root__/initializers/__name__.js
tests/dummy/app/initializers/author.js
tests/dummy/app/initializers/comment.js
tests/dummy/app/initializers/commenter.js
tests/dummy/app/initializers/employee.js
tests/dummy/app/initializers/imageable.js
tests/dummy/app/initializers/picture.js
tests/dummy/app/initializers/post.js
tests/dummy/app/initializers/product.js
tests/dummy/app/routes/admin/create.js
tests/helpers/resources.js
tests/unit/adapters/application-test.js
tests/unit/models/resource-test.js
tests/unit/serializers/application-test.js
tests/unit/utils/has-many-test.js
tests/unit/utils/has-one-test.js

- Fix factory lookups to use singular naming for model factory
- Remove injections from initializer blueprint, standard registry naming is fine
- service still uses plural name (common naming for an api endpoint anyway)

Simplify initializer, use standard naming for factories

---

addon/adapters/application.js
tests/dummy/app/components/form-post.js
tests/dummy/app/controllers/admin/edit.js
tests/dummy/app/templates/admin/edit.hbs
tests/unit/adapters/application-test.js

The more common use case is to just call the updateResource method vs. auto-update
- No more magic calls to the adapters' `updateResource` method via `attributeChanged` events
- If developers want to use the events they can define the behavior based on the `attributeChanged` event
- Added example behavior to dummy app for updateResource and rollback on fail

[Breaking] Remove Adapter#initEvents use #updateResource explicitly

---

addon/models/resource.js
addon/utils/has-many.js
addon/utils/has-one.js
addon/utils/related-proxy.js
tests/unit/adapters/application-test.js
tests/unit/models/resource-test.js
tests/unit/utils/has-many-test.js
tests/unit/utils/has-one-test.js

Keeps relationship[relation].data updated on the resource instance following resolution of promise proxy for relations.

Add Resource#didResolveProxyRelation method to maintain data linkage

---

blueprints/addon-import/index.js
blueprints/jsonapi-dictionary-test/files/tests/unit/utils/dictionaries/__name__-test.js
blueprints/jsonapi-dictionary-test/index.js
blueprints/jsonapi-dictionary/files/__root__/utils/dictionaries/__name__.js
blueprints/jsonapi-dictionary/index.js
blueprints/jsonapi-initializer/index.js
blueprints/jsonapi-transform-test/files/tests/unit/__path__/__test__.js
blueprints/jsonapi-transform-test/index.js
blueprints/jsonapi-transform/files/__root__/__path__/__name__.js
blueprints/jsonapi-transform/index.js

- Add blueprint for dictionary util to use with transform objects
- Add value transforms blueprint, uses util/dictionaries
New blueprints are to support custom types, perhaps to support an enum field in your database.
See:
- https://github.com/pixelhandler/ember-jsonapi-resources/wiki/Transforms
- https://github.com/pixelhandler/ember-jsonapi-resources/wiki/Enum-Attributes

Add blueprints for transforms and util/dictionaries

---

blueprints/addon-import/index.js
blueprints/jsonapi-model-test/index.js
blueprints/jsonapi-serializer-test/index.js
blueprints/jsonapi-transform-mixin/files/__root__/mixins/__name__.js
blueprints/jsonapi-transform-mixin/index.js

The `jsonapi-transform-mixin` generates a mixin to use with your serializer for specific attributes that you have transform objects for.
Example workflow for adding a custom transform for the status attribute of a post resource (model):
ember g jsonapi-dictionary status active:Active pending:Pending archived:Archive
ember g jsonapi-transform status
ember g jsonapi-transform-mixin post status
See: https://github.com/pixelhandler/ember-jsonapi-resources/wiki/Transforms

Add blueprint for transforms mixin to use with serializers

---

addon/mixins/fetch.js
addon/utils/errors.js
tests/unit/adapters/application-test.js
tests/unit/mixins/fetch-test.js

- Add HTTP status code as a property of the custom error objects.
- Change arguments for FetchError to use `response` or `error` as 2nd argument, remove 3rd argument.
- Use common error messaging/formatting methods for custom error types based on request type (fetch/xhr)

Add code property to custom errors

---

addon/adapters/application.js
addon/models/resource.js
addon/utils/related-proxy.js
tests/helpers/resources.js
tests/unit/adapters/application-test.js
tests/unit/models/resource-test.js
tests/unit/serializers/application-test.js

Enhances behavior of adding and removing relationships to a resource.
On a Resource object, with related (computed properties) proxy objects, the `addRelationship` and `removeRelationship` will utilize the related service's cache data to add (assign) or remove the related resource via the `content` of the related proxy object. Resource objects that have `isNew` set to true will use proxy objects as well, (no related promise proxy, only a proxy). Creating a resource with relations requires the `relationships` object to include a `links` object with a `related` property that is the URL for the relationship data.

Assign relations to computed properties that use a proxy object

---

questions/index.html

Fixes a few typos in the docs
- `adaters` -> `adapters`
- `exiration` -> `expiration`

Fix typos on questions page

---

addon/utils/related-proxy.js
tests/unit/utils/has-one-test.js

Lookup result for cached content can be an object or an array, remove condition that only returned cache for an array result.

Fix promise from cache for related proxy

---

app/blueprints/ember-jsonapi-resources.js
app/blueprints/resource.js
blueprints/jsonapi-adapter/files/__root__/__path__/__name__.js
blueprints/jsonapi-adapter/index.js
blueprints/jsonapi-blueprint/files/blueprints/.jshintrc
blueprints/jsonapi-blueprint/files/blueprints/__name__/index.js
blueprints/jsonapi-blueprint/index.js
blueprints/jsonapi-initializer/index.js
blueprints/jsonapi-model/files/__root__/__path__/__name__.js
blueprints/jsonapi-model/index.js
blueprints/jsonapi-resource/index.js
blueprints/jsonapi-serializer/index.js
blueprints/jsonapi-service/index.js

- Use relative path for config in adapter blueprint
- Add `__root__` blueprints, used inside addon the root will be `app` where needed
- Resource blueprint uses app and addon files for models
- Add `jsonapi-blueprint` to generate blueprints for addons (name of the addon)
- Generated blueprints add the `ember-jsonapi-resources` package to consuming project in `afterInstall`
- Model blueprint imports `resource` using full path (from addon directory)
- Add `getDefaults` class method in Model blueprint

Tune up blueprints, use in addons, add jsonapi-blueprint

---

addon/adapters/application.js
addon/models/resource.js
tests/dummy/app/models/author.js
tests/dummy/app/models/comment.js
tests/dummy/app/models/commenter.js
tests/dummy/app/models/employee.js
tests/dummy/app/models/person.js
tests/dummy/app/models/post.js
tests/dummy/app/models/supervisor.js
tests/dummy/config/environment.js
tests/helpers/resources.js
tests/unit/adapters/application-test.js
tests/unit/mixins/resource-operations-test.js
tests/unit/models/resource-test.js
tests/unit/serializers/application-test.js

This PR is intended to review/discuss changes.

Improve test setup

---

blueprints/ember-jsonapi-resources/index.js

Addon is broken with latest versions of es6-promise, because of wrong import. This PR is fixed es6-promise package version to 3.0.2

Fix es6-promise bower dependency

---

addon/adapters/application.js
addon/models/resource.js
addon/serializers/application.js
addon/services/store.js
bower.json
tests/unit/adapters/application-test.js
tests/unit/models/resource-test.js
tests/unit/serializers/application-test.js

- Add relationship change tracking to the Resource
- Add `rollbackRelationships` method
- Change `rollback` to call both `rollbackAttributes` and `rollbackRelationships`
- Add `changedRelationships` property and `relationMetadata` method to Resource
- Add new relationship serialization methods
- Add optional second parameter `includeRelationships ` to `ApplicationAdapter#updateResource` method to patch relationships
- Opt into what relationships to patch using an array of the relationships (names, e.g. `['author', 'comments']`

Update relationships with resource

---

addon/adapters/application.js
addon/models/resource.js

- Prevent redundant change tracking
- Cleanup tracking after persisting changes

Cleanup relationship change tracking

---

addon/models/resource.js

Small improvement: re-throw error if we can't fall back on ObjectProxy. This brings up very useful error messages like `Assertion Failed: metaForProperty() could not find a computed property with key 'bonus-malus-table'.`, in this case caused by an undefined relationship clientside.

Improve relationMetadata error handling/throwing

---

blueprints/ember-jsonapi-resources/index.js
bower.json
index.js

Bump dependency for es6-promise to 4.0.5 and change the location and name of where to find the file.

Fix for using ember-json-api-resources with es6-promise 3.2.x and above.

---

addon/models/resource.js
tests/unit/models/resource-test.js

bugfix: Track changed hasOne without 'previous'

---

.travis.yml
addon/adapters/application.js
addon/mixins/adapter-api-host-proxy.js
addon/models/resource.js
addon/serializers/application.js
blueprints/jsonapi-model-test/files/tests/unit/__path__/__test__.js
blueprints/jsonapi-serializer-test/files/tests/unit/__path__/__test__.js
config/ember-try.js
tests/dummy/app/routes/admin/create.js
tests/helpers/resources.js
tests/unit/adapters/application-test.js
tests/unit/mixins/service-cache-test.js
tests/unit/models/resource-test.js
tests/unit/serializers/application-test.js
tests/unit/utils/has-many-test.js
tests/unit/utils/has-one-test.js

Remove usage of this.container.
This will make the addon only work with Ember.js > 2.3 and will most likely want a major version bump after this is merged in.

Remove usage of this.container completely.

---

addon/adapters/application.js

In the upgrade to use fetchjax addon the ability is lost to configure it to default to ajax.  This brings that functionality back.

Allow flag useAjax to disable fetch

---

addon/mixins/resource-operations.js
addon/models/resource.js
tests/unit/mixins/resource-operations-test.js
tests/unit/models/resource-test.js

- Add new private method on model to replace relations
- Update tests for updateRelationship behaviors

updateRelationship replaces relations

---

tests/unit/models/resource-test.js

Current behavior is to stash an attribute’s value on EVERY call to .set(). The intent seems to be to rollback to the value fetched from the persistence layer.
As illustrated by the tests:
```
post.get(‘excerpt’); // ‘Was a gambler.’
post.set('excerpt', 'Became the sheriff.');
post.set('excerpt', 'Became the chief.');
post.set('excerpt', 'Became the mayor.');
post.get('previousAttributes.excerpt’); // 'Became the chief.'
```
The previous value is simply the previous change ('Became the chief’) instead of the “original” value (“Was a gambler”).
The new tests FAIL to show that “previousAttributes” and “rollbackAttributes” to not behave as expected.

Failing tests for previousAttributes/rollbackAttributes

---

addon/utils/attr.js

Without this, changes in attributes of type `object` and `array` are never tracked, since they are simply referenced as/to `changed` and `previous`, so they are always the same.
Copying the objects will actually detect the changes in these attributes. 
Might not be the best idea performance-wise, but there are probably very few complicated/large arrays or objects that are simply attributes on a model/resource, and relationship changes are tracked seperately.

Ember.copy values to 'changed' and 'previous'
